/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[link_name = "\u{1}_Z14DrawChessboardii"]
    pub fn DrawChessboard(width: ::std::os::raw::c_int, height: ::std::os::raw::c_int);
}
