/* automatically generated by rust-bindgen 0.59.1 */

#![allow(warnings)]

extern "C" {
    #[link_name = "\u{1}_Z10CountLuckyPKcS0_S0_"]
    pub fn CountLucky(
        range_start: *const ::std::os::raw::c_char,
        range_end: *const ::std::os::raw::c_char,
        city_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_Z7IsLuckyPKcS0_"]
    pub fn IsLucky(
        ticket_num: *const ::std::os::raw::c_char,
        city_name: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}_Z11IsCityValidPKc"]
    pub fn IsCityValid(city_name: *const ::std::os::raw::c_char) -> bool;
}
